---
- name: update apt cache
  apt: update_cache=yes
- name: update packages
  apt: upgrade=yes
- name: update distribution
  apt: upgrade=dist
- name: install software-properties-common
  apt: name=software-properties-common state=latest update_cache=yes

