---
- name: install python-mysqldb
  apt: name=python-mysqldb state=latest update_cache=yes
- name: install mysql
  apt: name=mysql-server state=latest update_cache=yes
- name: Start the MySQL service
  action: service name=mysql state=started
